// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvosudgadzruqelyfxah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2b3N1ZGdhZHpydXFlbHlmeGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMjc1ODIsImV4cCI6MjA4NDcwMzU4Mn0.W0HqsZWXV6KNrIpHZouMdTnQAM9kCneeHG_Yk23UdfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});